---
- name: ZABBIX 5.0 | Download Package rpm
  yum:
     name: https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
     state: present

- name: ZABBIX 5.0 | yum clean command
  command: yum clean all

 
- name: ZABBIX 5.0 | Install Zabbix Packages
  yum:
     name: 
        - zabbix-server-pgsql 
        - zabbix-agent
        - zabbix-get
        - zabbix-sender
     state: installed 

- name: ZABBIX 5.0 | Zabbix Frontend Packages
  yum:
     name: centos-release-scl
     state: installed

- name: ZABBIX 5.0 | Zabbix Frontend Repo Enable
  template: src=zabbix.j2 dest={{ zabbix_repo_folder }}/zabbix.repo mode=0644

- name: ZABBIX 5.0 | Install Frontend Packages
  yum:
     name: 
       - zabbix-web-pgsql-scl
       - zabbix-apache-conf-scl
     state: installed

- name: ZABBIX 5.0 | Import SQL Scheme for zabbix user
  command: zcat /usr/share/doc/zabbix-server-pgsql*/create.sql.gz | sudo -u {{ db_user }} psql {{ db_pass }}
  register: command_result
  failed_when: "'FAILED' in command_result.stderr"

- name: ZABBIX 5.0 | Change zabbix.conf
  template: src=zabbix_server.j2 dest={{ zabbix_server_folder }}/zabbix_server.conf mode=664

- name: ZABBIX 5.0 | Change php timezone
  template: src=timezone.j2 dest={{ php_timezone }}/zabbix.conf mode=0644

- name: ZABBIX 5.0 | Enable all Packages
  command: systemctl restart zabbix-server zabbix-agent httpd rh-php72-php-fpm

- name: ZABBIX 5.0 | Restart all Packages
  command: systemctl restart zabbix-server zabbix-agent httpd rh-php72-php-fpm
